/*
东东萌宠互助码
此文件为Node.js专用。其他用户请忽略
支持京东N个账号
 */
//云服务器腾讯云函数等NOde.js用户在此处填写东东萌宠的好友码。
// 同一个京东账号的好友互助码用@符号隔开,不同京东账号之间用&符号或者换行隔开,下面给一个示例
// 如: 京东账号1的shareCode1@京东账号1的shareCode2&京东账号2的shareCode1@京东账号2的shareCode2
let PetShareCodes = [
  'MTAxODc2NTE0NzAwMDAwMDAyMTQ3NjU2Nw==@MTAxODc2NTE0NzAwMDAwMDAyMDkyMzE3MQ==@MTE1NDQ5OTUwMDAwMDAwNDM5MDcyMDk=@MTE1NDUyMjEwMDAwMDAwNDM5MzAxNjE=@MTAxODc2NTEzMDAwMDAwMDAxMzkxMTc2Mw==@MTE1MzEzNjI2MDAwMDAwMDU1NzgyMTI5@MTEyOTEzNzMzMDAwMDAwMDUzNzI5MDYx@MTE1NDY3NTIwMDAwMDAwNTQxMTQ4MTc=@MTE5MzEwNTEzODAwMDAwMDA1MzcyODk4OQ==@MTAxNzIyNTU1NDAwMDAwMDA1MzcyOTA4Mw==@MTEzMzI1MTE4NDAwMDAwMDA1MzcyOTExNw==@MTAxNzIyNTU1NDAwMDAwMDA1MzYyMzY1Mw==@MTEyNjE4NjQ2MDAwMDAwMDUzNjIzNjc5@MTEyNjE4NjQ2MDAwMDAwMDUzNzUzMDgz@MTEyNjE4NjQ2MDAwMDAwMDUzODMzNzEz@MTEyNzEzMjc0MDAwMDAwMDU1NDUyOTY5@MTEzMzI1MTE4NDAwMDAwMDA1MzgzMzczNw==@MTEyNjkzMjAwMDAwMDAwMDUzODMzNzY3@MTAxNzIxMDc1MTAwMDAwMDA1NTQ1MzAwMQ==@MTE1NDY3NTMwMDAwMDAwNTMyNDM0NTk=@MTEzMzI1MTE4NDAwMDAwMDA1NDA2NDk3Nw==@MTEzMzI1MTE4NDAwMDAwMDA1NDA2NDk4NQ==@MTEyNjkzMjAwMDAwMDAwMDU0MDY0OTk3@MTEyOTEzNzMzMDAwMDAwMDUzNTQ4NDE3@MTE1NDY3NTIwMDAwMDAwNTM1NDgzNzM=@MTEyNzEzMjc0MDAwMDAwMDUzNTQ4Mzkz@MTEzMzI1MTE4NTAwMDAwMDA1MzY0NTg4Mw==@MTEzMzI1MTE4NDAwMDAwMDA1MzY0NTg5Nw==@MTE5MzEwNTEzODAwMDAwMDA1MzY0NTkwMw==@MTE1NDY3NTMwMDAwMDAwNTM3NTM5Njk=@MTEyNjkzMjAwMDAwMDAwMDUzNjIzNTc3@MTE1NDY3NTMwMDAwMDAwNTU3ODE5NjU=@MTEyNjkzMjAwMDAwMDAwMDU0ODI1NjUz@MTEzMzI1MTE4NDAwMDAwMDA1NTc4MjAyMQ==@MTE1NDY3NTMwMDAwMDAwNTU3ODIwNTU=@MTEyOTEzNzMzMDAwMDAwMDU1NzgyMTAx@MTEyOTEzNzMzMDAwMDAwMDU1ODIwOTM3@MTEzMzI1MTE4NDAwMDAwMDA1NTgyMDk1MQ==@MTEyOTEzNzMzMDAwMDAwMDU0NTE4MTY5@MTE5MzEwNTEzODAwMDAwMDA1NTgyMDk3NQ==@MTEyNzEzMjc0MDAwMDAwMDU1ODIwOTg5@MTAxNzIxMDc1MTAwMDAwMDA1NTk1NzA2NQ==@MTEzMzI1MTE4NDAwMDAwMDA1NTk1NzA4MQ==@MTE1NDY3NTMwMDAwMDAwNTU5NTcwODk=@MTE1NDY3NTIwMDAwMDAwNTU5NTcxMDM=@MTEyOTEzNzMzMDAwMDAwMDU2MDU4MzY5@MTEzMzI1MTE4NTAwMDAwMDA1Njc5MzIxMw==@MTE1NDY3NTIwMDAwMDAwNTM2Mzg3OTU=@MTEyNjkzMjAwMDAwMDAwMDU2MDU4Mzk1@MTE1NDY3NTMwMDAwMDAwNTY2NTY1NTk=@MTE5MzEwNTEzODAwMDAwMDA1NjY1NjU3Mw==@MTEyNzEzMjc0MDAwMDAwMDU2NzkzMjUz',//账号一的好友shareCode,不同好友中间用@符号隔开
  'MTAxODc2NTE0NzAwMDAwMDAyMTQ3NjU2Nw==@MTAxODc2NTE0NzAwMDAwMDAyMDkyMzE3MQ==@MTE1NDQ5OTUwMDAwMDAwNDM5MDcyMDk=@MTE1NDUyMjEwMDAwMDAwNDM5MzAxNjE=@MTAxODc2NTEzMDAwMDAwMDAxMzkxMTc2Mw==@MTE1MzEzNjI2MDAwMDAwMDU1NzgyMTI5@MTEyOTEzNzMzMDAwMDAwMDUzNzI5MDYx@MTE1NDY3NTIwMDAwMDAwNTQxMTQ4MTc=@MTE5MzEwNTEzODAwMDAwMDA1MzcyODk4OQ==@MTAxNzIyNTU1NDAwMDAwMDA1MzcyOTA4Mw==@MTEzMzI1MTE4NDAwMDAwMDA1MzcyOTExNw==@MTAxNzIyNTU1NDAwMDAwMDA1MzYyMzY1Mw==@MTEyNjE4NjQ2MDAwMDAwMDUzNjIzNjc5@MTEyNjE4NjQ2MDAwMDAwMDUzNzUzMDgz@MTEyNjE4NjQ2MDAwMDAwMDUzODMzNzEz@MTEyNzEzMjc0MDAwMDAwMDU1NDUyOTY5@MTEzMzI1MTE4NDAwMDAwMDA1MzgzMzczNw==@MTEyNjkzMjAwMDAwMDAwMDUzODMzNzY3@MTAxNzIxMDc1MTAwMDAwMDA1NTQ1MzAwMQ==@MTE1NDY3NTMwMDAwMDAwNTMyNDM0NTk=@MTEzMzI1MTE4NDAwMDAwMDA1NDA2NDk3Nw==@MTEzMzI1MTE4NDAwMDAwMDA1NDA2NDk4NQ==@MTEyNjkzMjAwMDAwMDAwMDU0MDY0OTk3@MTEyOTEzNzMzMDAwMDAwMDUzNTQ4NDE3@MTE1NDY3NTIwMDAwMDAwNTM1NDgzNzM=@MTEyNzEzMjc0MDAwMDAwMDUzNTQ4Mzkz@MTEzMzI1MTE4NTAwMDAwMDA1MzY0NTg4Mw==@MTEzMzI1MTE4NDAwMDAwMDA1MzY0NTg5Nw==@MTE5MzEwNTEzODAwMDAwMDA1MzY0NTkwMw==@MTE1NDY3NTMwMDAwMDAwNTM3NTM5Njk=@MTEyNjkzMjAwMDAwMDAwMDUzNjIzNTc3@MTE1NDY3NTMwMDAwMDAwNTU3ODE5NjU=@MTEyNjkzMjAwMDAwMDAwMDU0ODI1NjUz@MTEzMzI1MTE4NDAwMDAwMDA1NTc4MjAyMQ==@MTE1NDY3NTMwMDAwMDAwNTU3ODIwNTU=@MTEyOTEzNzMzMDAwMDAwMDU1NzgyMTAx@MTEyOTEzNzMzMDAwMDAwMDU1ODIwOTM3@MTEzMzI1MTE4NDAwMDAwMDA1NTgyMDk1MQ==@MTEyOTEzNzMzMDAwMDAwMDU0NTE4MTY5@MTE5MzEwNTEzODAwMDAwMDA1NTgyMDk3NQ==@MTEyNzEzMjc0MDAwMDAwMDU1ODIwOTg5@MTAxNzIxMDc1MTAwMDAwMDA1NTk1NzA2NQ==@MTEzMzI1MTE4NDAwMDAwMDA1NTk1NzA4MQ==@MTE1NDY3NTMwMDAwMDAwNTU5NTcwODk=@MTE1NDY3NTIwMDAwMDAwNTU5NTcxMDM=@MTEyOTEzNzMzMDAwMDAwMDU2MDU4MzY5@MTEzMzI1MTE4NTAwMDAwMDA1Njc5MzIxMw==@MTE1NDY3NTIwMDAwMDAwNTM2Mzg3OTU=@MTEyNjkzMjAwMDAwMDAwMDU2MDU4Mzk1@MTE1NDY3NTMwMDAwMDAwNTY2NTY1NTk=@MTE5MzEwNTEzODAwMDAwMDA1NjY1NjU3Mw==@MTEyNzEzMjc0MDAwMDAwMDU2NzkzMjUz',//账号二的好友shareCode，不同好友中间用@符号隔开
]

// 从日志获取互助码
const logShareCodes = require('./utils/jdShareCodes');
// if (logShareCodes.PETSHARECODES.length > 0 && !process.env.PETSHARECODES) {
//   process.env.PETSHARECODES = logShareCodes.PETSHARECODES.join('&');
// }

// 判断github action里面是否有东东萌宠互助码
if (process.env.PETSHARECODES) {
  if (process.env.PETSHARECODES.indexOf('&') > -1) {
    console.log(`您的东东萌宠互助码选择的是用&隔开\n`)
    PetShareCodes = process.env.PETSHARECODES.split('&');
  } else if (process.env.PETSHARECODES.indexOf('\n') > -1) {
    console.log(`您的东东萌宠互助码选择的是用换行隔开\n`)
    PetShareCodes = process.env.PETSHARECODES.split('\n');
  } else {
    PetShareCodes = process.env.PETSHARECODES.split();
  }
} else {
  console.log(`由于您环境变量(PETSHARECODES)里面未提供助力码，故此处运行将会给脚本内置的码进行助力，请知晓！`)
}
for (let i = 0; i < PetShareCodes.length; i++) {
  const index = (i + 1 === 1) ? '' : (i + 1);
  exports['PetShareCode' + index] = PetShareCodes[i];
}