name: 抖音极速版日常
 
on:
  workflow_dispatch:
  schedule:
      #每小时允许一次
     - cron: '0 */1 * * *'
    watch:
        types: [started]
    repository_dispatch:
        types: douyin
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
            node-version: 10.x
      - name: npm install
        run: |
            npm install
      - name: '运行 【抖音极速版】'
        run: |
          node douyin.js
        env:
          DYJSB_COOKIE: ${{ secrets.DYJSB_COOKIE }} #必须 cookie 多账号
