name: 抖音极速版

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"
  watch:
    types: started
  repository_dispatch:
    types: douyin

jobs:
  build:
    name: 抖音极速版_ubuntu系统
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: 运行【抖音极速版】
        run: |
          node douyin.js
        env:
          DYJSB_COOKIE: ${{ secrets.DYJSB_COOKIE }}
