# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 抖音极速版

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"
  watch:
    types: started
  repository_dispatch:
    types: douyin
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: "运行 【抖音极速版】"
        run: |
          node onlyOneExecute.js
        env:
          DYJSB_COOKIE: ${{ github.event.client_payload.DYJSB_COOKIE ||  secrets.DYJSB_COOKIE }}
          SYNCURL: https://github.com/h455257166/My_Script/raw/main/douyin.js



