name: 抖音极速版

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"
  watch:
    types: started

jobs:
  build:
    name: 安装最新版ubantu系统
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      -name: 运行【抖音极速版】
        run: |
          node https://github.com/h455257166/My_Script/JSActionsScripts/douyin.js
        env:
          DYJSB_COOKIE:${{ secrets.DYJSB_COOKIE || github.event.client_payload.DYJSB_COOKIE }}
